{
 "title": "hf llm dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Client Side Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "(C) Request per second ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(hf_enduser_requests_counter_total[$__rate_interval])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "(C) Generated vs Prompt token per sec",
   "type": "timeseries",
   "description": "Number of tokens generated per second and the number of prompt tokens per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(hf_generated_token_counter_total[$__rate_interval])",
     "legendFormat": "Generated Tokens"
    },
    {
     "expr": "rate(hf_prompt_token_counter_total[$__rate_interval])",
     "legendFormat": "Prompt Tokens"
    }
   ]
  },
  {
   "title": "(C) Inference Latency - milliseconds/generated token ",
   "type": "timeseries",
   "description": "Graphs the inference latency, showing the number of microseconds for each token generation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(hf_request_processing_seconds_sum[$__rate_interval])*1000/rate(hf_generated_token_counter_total[$__rate_interval])",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": "(C) Avg generated and prompt tokens per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(hf_generated_token_counter_total[$__rate_interval])/rate(hf_enduser_requests_counter_total[$__rate_interval])",
     "legendFormat": "generated tokens"
    },
    {
     "expr": "rate(hf_prompt_token_counter_total[$__rate_interval])/rate(hf_enduser_requests_counter_total[$__rate_interval])",
     "legendFormat": "prompt tokens"
    }
   ]
  }
 ]
}